version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Huynguyen11102002
    volumes:
      - mariadb_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  springbootapp:
    image: spring-boot-lib-image
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/qltvdemo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Huynguyen11102002
    ports:
      - "9000:9000"

volumes:
  mariadb_data:
